#!/bin/bash
# ---------------------------------------------------------------------------
#
# Hilfsprogramm für das Aktivieren/Deaktivieren der verschiedenen Optionen.
#
# Autor: Bernhard Bablok
# Lizenz: GPL3
#
# Website: https://github.com/bablokb/fuchsfalle
#
# ---------------------------------------------------------------------------

do_help() {
cat <<EOF
Mögliche Parameter:

help    - diese Hilfe

aktiv       - Konfiguration AKTIV=1 setzen
inaktiv     - Konfiguration AKTIV=0 setzen
pin         - Setzen der Pin
sms         - Setzen der SMS-Nummer (SMS_NR)
admin       - Setzen der Admin-Nummern (SMS_ADMIN)
fnr         - Setzen der Nummer/des Texts der Fuchsfalle

syslog      - Anzeige Systemlog-Meldungen
log         - Anzeige /var/log/fuchsfalle.log
rclog       - Anzeige /var/log/rc.log

send        - Senden von SMS aktivieren
nosend      - Senden von SMS deaktivieren
halt        - Herunterfahren aktivieren
nohalt      - Herunterfahren deaktivieren

powerset    - Variable für Powersave setzen (Argumente: Variable Wert)
powersave   - Alle konfigurierten Mechanismen aktivieren
nopowersave - Alle konfigurierten Mechanismen deaktivieren

scharf      - Scharfschalten des Pi (entspricht "aktiv send halt powersave")
EOF

exit 0
}

# --- -----------------------------------------------------------------------

do_aktiv() {
  sed -i -e '/AKTIV/s/AKTIV="."/AKTIV="1"/' /boot/fuchsfalle.cfg
}

# --- -----------------------------------------------------------------------

do_inaktiv() {
  sed -i -e '/AKTIV/s/AKTIV="."/AKTIV="0"/' /boot/fuchsfalle.cfg
}

# --- -----------------------------------------------------------------------

do_pin() {
  sed -i -e "/PIN/s/PIN=\".*\"/PIN=\"$1\"/" /boot/fuchsfalle.cfg
  if [ -z "$1" ]; then
    echo "Warnung: Pinnummer gelöscht" >&2
  fi
}

# --- -----------------------------------------------------------------------

do_sms() {
  if [ -z "$1" ]; then
    echo "Fehler: SMS-Nummer fehlt" >&2
  else
    sed -i -e "/SMS_NR/s/SMS_NR=\".*\"/SMS_NR=\"$1\"/" /boot/fuchsfalle.cfg
  fi
}

# --- -----------------------------------------------------------------------

do_admin() {
  sed -i -e "/SMS_ADMIN/s/SMS_ADMIN=\".*\"/SMS_ADMIN=\"$1\"/" /boot/fuchsfalle.cfg
  if [ -z "$1" ]; then
    echo "Warnung: SMS_ADMIN-Nummer gelöscht" >&2
  fi
}

# --- -----------------------------------------------------------------------

do_fnr() {
  if [ -z "$1" ]; then
    echo "Fehler: Nummer/Text fehlt" >&2
    return
  fi
  sed -i -e "/FNR/s/FNR=\".*\"/FNR=\"$1\"/" /boot/fuchsfalle.cfg
}

# --- -----------------------------------------------------------------------

do_syslog() {
  journalctl SYSLOG_IDENTIFIER=rc.local SYSLOG_IDENTIFIER=fuchsfalle.sh
}

# --- -----------------------------------------------------------------------

do_rclog() {
    cat /var/log/rc.log
}

# --- -----------------------------------------------------------------------

do_log() {
  cat /var/log/fuchsfalle.log
}

# --- -----------------------------------------------------------------------

do_nosend() {
  if [ -f /boot/nosendno ]; then
    mv -f /boot/nosendno /boot/nosend
  else
    touch /boot/nosend
  fi
}

# --- -----------------------------------------------------------------------

do_send() {
  mv -f /boot/nosend /boot/nosendno
}

# --- -----------------------------------------------------------------------

do_nohalt() {
  if [ -f /boot/nohaltno ]; then
    mv -f /boot/nohaltno /boot/nohalt
  else
    touch /boot/nohalt
  fi
}

# --- -----------------------------------------------------------------------

do_halt() {
  mv -f /boot/nohalt /boot/nohaltno
}

# --- -----------------------------------------------------------------------
do_powerset() {
  local var="$1" wert="$2"
  if [ -z "$var" ]; then
    echo "Fehler: Argumente 'Variable Wert' fehlen" >&2
  elif [ -z "$wert" ]; then
    echo "Fehler: Argument 'Wert' fehlt" >&2
  else
    sed -i -e "/$var/s/$var=\".*\"/$var=\"$wert\"/" /boot/fuchsfalle.cfg
  fi
}

# --- -----------------------------------------------------------------------
do_powersave() {
  systemctl start fuchspower.service
}

# --- -----------------------------------------------------------------------
do_nopowersave() {
  systemctl stop fuchspower.service
}

# --- -----------------------------------------------------------------------

do_scharf() {
  do_aktiv
  do_send
  do_halt
  do_powersave
}

# --- Hauptprogramm   -------------------------------------------------------

if [ -z "$1" ]; then
  do_help
fi

task="$1"
shift
do_$task "$@"
