#!/bin/bash
# ---------------------------------------------------------------------------
#
# Hilfsprogramm für das Aktivieren/Deaktivieren der verschiedenen Optionen.
#
# Autor: Bernhard Bablok
# Lizenz: GPL3
#
# Website: https://github.com/bablokb/fuchsfalle
#
# ---------------------------------------------------------------------------

do_help() {
cat <<EOF
Mögliche Parameter:

help    - diese Hilfe
aktiv   - Konfiguration AKTIV=1 setzen
inaktiv - Konfiguration AKTIV=0 setzen
pin     - Setzen der Pin
sms     - Setzen der SMS-Nummer (SMS_NR)
admin   - Setzen der Admin-Nummern (SMS_ADMIN)
send    - Senden von SMS aktivieren
nosend  - Senden von SMS deaktivieren
halt    - Herunterfahren aktivieren
nohalt  - Herunterfahren deaktivieren
sharf   - Scharfschalten des Pi (entspricht "aktiv send halt")
EOF

exit 0
}

# --- -----------------------------------------------------------------------

do_aktiv() {
  sed -i -e '/AKTIV/s/AKTIV="."/AKTIV="1"/' /boot/fuchsfalle.cfg
}

# --- -----------------------------------------------------------------------

do_inaktiv() {
  sed -i -e '/AKTIV/s/AKTIV="."/AKTIV="0"/' /boot/fuchsfalle.cfg
}

# --- -----------------------------------------------------------------------

do_pin() {
  if [ -z "$1" ]; then
    echo "error: Pinnummer fehlt"
  else
    sed -i -e "/PIN/s/PIN=\".*\"/PIN=\"$1\"/" /boot/fuchsfalle.cfg
  fi
}

# --- -----------------------------------------------------------------------

do_sms() {
  if [ -z "$1" ]; then
    echo "error: SMS-Nummer fehlt"
  else
    sed -i -e "/SMS_NR/s/SMS_NR=\".*\"/SMS_NR=\"$1\"/" /boot/fuchsfalle.cfg
  fi
}

# --- -----------------------------------------------------------------------

do_admin() {
  if [ -z "$1" ]; then
    echo "error: SMS_ADMIN-Nummer fehlt"
  else
    sed -i -e "/SMS_ADMIN/s/SMS_ADMIN=\".*\"/SMS_ADMIN=\"$1\"/" /boot/fuchsfalle.cfg
  fi
}

# --- -----------------------------------------------------------------------

do_log() {
  if [ -z "$1" ]; then
    echo "error: Log-Type (syslog|rc.local|fuchsfalle) fehlt"
  elif [ "$1" = "syslog" ]; then
    journalctl SYSLOG_IDENTIFIER=rc.local SYSLOG_IDENTIFIER=fuchsfalle.sh
  elif [ "$1" = "rc.local" ]; then
    cat /var/log/rc.log
  elif [ "$1" = "fuchsfalle" ]; then
    cat /var/log/fuchsfalle.log
  fi
}

# --- -----------------------------------------------------------------------

do_nosend() {
  touch /boot/nosend
}

# --- -----------------------------------------------------------------------

do_send() {
  rm -f /boot/nosend
}

# --- -----------------------------------------------------------------------

do_nohalt() {
  touch /boot/nohalt
}

# --- -----------------------------------------------------------------------

do_halt() {
  rm -f /boot/nohalt
}

# --- -----------------------------------------------------------------------

do_scharf() {
  do_aktiv
  do_send
  do_halt
}

# --- Hauptprogramm   -------------------------------------------------------

if [ -z "$1" ]; then
  do_help
fi

task="$1"
shift
do_$task "$@"
